# Generated by Django 5.0.6 on 2026-05-31 13:16

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='ReportChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='reports.medicalreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_chunks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['report_id', 'chunk_index'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='reportchunk_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
